#
# Common part 
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: es-cl-01
---
apiVersion: v1
kind: Service
metadata:
  name: masters-cluster-ip
  namespace: es-cl-01
  labels:
    app.name: elastic
spec:
  selector:
    app.name: elastic
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: http-elastic-client
#
# master nodes 
#
---
apiVersion: v1
kind: Service
metadata:
  name: masters-headless
  namespace: es-cl-01
  labels:
    app.name: elastic
    app.pods-role: masters
spec:
  clusterIP: None
  selector:
    app.name: elastic
    app.pods-role: masters
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-master
  namespace: es-cl-01
spec:
  serviceName: masters-headless
  replicas: 3
  selector:
    matchLabels:
      app.name: elastic
      app.pods-role: masters
  template:
    metadata:
      labels:
        app.name: elastic
        app.pods-role: masters
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.pods-role
                operator: In
                values:
                - masters
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
        resources:
            limits:
              cpu: 2000m
              memory: 370Mi
            requests:
              cpu: 300m
              memory: 340Mi
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: pvc
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: es-cl-01
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: "cluster.initial_master_nodes"
            value: "es-master-0, es-master-1, es-master-2"
          - name: "discovery.seed_hosts"
            value: "masters-headless"
          - name: "node.master"
            value: "true"
          - name: "node.voting_only"
            value: "false"
          - name: "node.data"
            value: "false"
          - name: "node.ingest"
            value: "false"
          - name: "node.ml"
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms100m -Xmx100m"
      initContainers:
      - name: fix-permissions
        image: busybox
        resources:
            limits:
              cpu: 200m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: pvc
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        resources:
            limits:
              cpu: 200m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: pvc
      labels:
        app.name: elastic
        app.pods-role: masters
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: pv-localdisks
      resources:
        requests:
          storage: 90Mi
#
# data nodes
#
---
apiVersion: v1
kind: Service
metadata:
  name: data-headless
  namespace: es-cl-01
  labels:
    app.name: elastic
    app.pods-role: data
spec:
  clusterIP: None
  selector:
    app.name: elastic
    app.pods-role: data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  namespace: es-cl-01
spec:
  serviceName: data-headless
  replicas: 6
  selector:
    matchLabels:
      app.name: elastic
      app.pods-role: data
  template:
    metadata:
      labels:
        app.name: elastic
        app.pods-role: data
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.pods-role
                  operator: In
                  values:
                  - data
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
        resources:
            limits:
              cpu: 2000m
              memory: 370Mi
            requests:
              cpu: 300m
              memory: 340Mi
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: pvc
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: es-cl-01
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: "discovery.seed_hosts"
            value: "masters-headless"
          - name: "node.master"
            value: "false"
          - name: "node.voting_only"
            value: "false"
          - name: "node.data"
            value: "true"
          - name: "node.ingest"
            value: "true"
          - name: "node.ml"
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms100m -Xmx100m"
      initContainers:
      - name: fix-permissions
        image: busybox
        resources:
            limits:
              cpu: 200m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: pvc
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        resources:
            limits:
              cpu: 200m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: pvc
      labels:
        app.name: elastic
        app.pods-role: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: pv-localdisks
      resources:
        requests:
          storage: 970Mi
#
# interface nodes
#
---
apiVersion: v1
kind: Service
metadata:
  name: interface
  namespace: es-cl-01
  labels:
    app.name: elastic
    app.pods-role: interface
spec:
  type: NodePort
  selector:
    app.name: elastic
    app.pods-role: interface
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: tcp-elastic-client
    nodePort: 30000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-interface
  namespace: es-cl-01
spec:
  serviceName: interface
  replicas: 3
  selector:
    matchLabels:
      app.name: elastic
      app.pods-role: interface
  template:
    metadata:
      labels:
        app.name: elastic
        app.pods-role: interface
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.pods-role
                operator: In
                values:
                - interface
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
        resources:
            limits:
              cpu: 2000m
              memory: 370Mi
            requests:
              cpu: 300m
              memory: 340Mi
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: pvc
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: es-cl-01
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: "discovery.seed_hosts"
            value: "masters-headless"
          - name: "node.master"
            value: "false"
          - name: "node.voting_only"
            value: "false"
          - name: "node.data"
            value: "true"
          - name: "node.ingest"
            value: "true"
          - name: "node.ml"
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms100m -Xmx100m"
      initContainers:
      - name: fix-permissions
        image: busybox
        resources:
            limits:
              cpu: 200m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: pvc
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        resources:
            limits:
              cpu: 200m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: pvc
      labels:
        app.name: elastic
        app.pods-role: interface
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: pv-localdisks
      resources:
        requests:
          storage: 90Mi
